baseurl=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

# LOGIN PAGE LOCATORS

# Input field for the username
username=//input[@name='username']
# Input field for the password
password=//input[@name='password']


# NAVIGATION / SIDEBAR LOCATORS

# PIM (Personnel Information Management) module in sidebar
pim=//span[text()='PIM']
# 'Add Employee' button within the PIM top navigation bar
addEmployee=//a[text()='Add Employee']

# ADD EMPLOYEE PAGE LOCATORS

firstName=//input[@name='firstName']
middleName=//input[@name='middleName']
lastName=//input[@name='lastName']


#Emp_Id
empid=(//input[contains(@class,'input')])[6]
# Toggle switch to 'Create Login Details' for the new employee
toggle=//span[contains(@class,'oxd-switch')]
# Input for Employee's custom system username
userName=//input[@autocomplete='off']
# Password and Confirmation fields for new employee login
passwordField=//input[@type='password']
confirmPassword=(//input[@type='password'])[2]
# Generic Save button used for form submission



# PERSONAL DETAILS / EDIT PAGE

# Nationality dropdown container and specific option
nationality=//label[text()='Nationality']/../following-sibling::div
indian=//span[text()='Indian']
# Gender radio button selection
male=//label[text()='Male']
# Marital Status dropdown container and specific option
marital=//label[text()='Marital Status']/../following-sibling::div
single=//span[text()='Single']

#RESUSABLE METHODS
subbutton=//button[@type='submit']
loader=//div[contains(@class,'oxd-form-loader')]
personalDetailsHeader=//h6[text()='Personal Details']
# USER PROFILE & LOGOUT

# Top-right user profile dropdown tab
profile=//span[@class='oxd-userdropdown-tab']
# Logout link within the profile dropdown menu
logout=//a[text()='Logout']