#Browser URL
BaseUrl=https://www.yatra.com/

# Title to be verified
ExpectedTitle=Domestic Flights Offers | Deals on Domestic Flight Booking | Yatra.com

# BannerText to be validated 
ExpectedBanner=Great Offers & Amazing Deals

# xpath of the popUp
popupCloseX=/html/body/div[1]/div/div[1]/div[1]/div[2]/div/section[2]/span/img

# xpath of the offersPage 
offersLink=//div[contains(text(),'View all offers')]

# xpath of the banner heading
bannerHeading=//h2[@class='wfull bxs']

# xpath of the Holidays Page
holidaysLink=Holidays

# cssSelector  of the package Titles
packageTitles=span.offerMainTitle