#This is Base URL
base_Url=https://www.rediff.com/
#create account hyperlink
landingpage.linktext = Create Account
#header of the create account page
createAccount.header = //h2[normalize-space()='Create a Rediffmail account']
#hyperlinks
createAccount.tagname = a
#terms and conditions hyperlink
createAccount.linktext = terms and conditions