#URL
baseUrl=https://www.rediff.com/

#Landing Page Title
landingPageTitle=Rediff.com: News | Rediffmail | Stock Quotes | Rediff Gurus

#browser
browser=chrome

#Alert Message
loginAlert=Please enter a valid user name
forgotAlert=Please enter your email ID

#Privacy Page Title
titlePrivacyPage=Rediff: Welcome to rediff.com