#baseUrl for navigation to website.
BaseUrl=https://www.quora.com/profile/Quora
  
#Passing initial value in searchbox for sign In.
Initialtesting=//input[@placeholder='Search content']
 
#xpath- Inputbox for search Element
SearchQuora=//input[@placeholder='Search Quora']
 
#Inputbox for Email
Emailby_id=#email
 
#valid EmailId
correctEmail=muddasanisaivarshith@gmail.com
 
#Inputbox for password
password_id=#password
 
#valid Password
correctPassword=Varshith@123
 
#xpath of login button.
Loginbutton=//div[@class='q-text qu-ellipsis qu-whiteSpace--nowrap'][normalize-space()='Login']
 
#Content for search
content=Testing
 
FirstSuggestion=//div[@id='selector-option-0']//div//div[@class='q-text qu-dynamicFontSize--regular']
#xpath for result text used for verification.
Result=//div[@class='q-box qu-borderBottom qu-pt--small qu-pb--small qu-bg--raised']//div[@class='q-text qu-dynamicFontSize--regular qu-medium qu-color--gray_dark qu-passColorToLinks']
 
#Expected result text
EXtext=Results for Testing
 
#xpath of nametag used for logout activity
Nametag=//div[@class='q-relative qu-display--inline-flex qu-alignItems--center qu-justifyContent--center']//div[@class='q-box qu-borderRadius--circle qu-borderAll qu-borderColor--darken']
 
#xpath of logout button
Logout=//div[contains(text(),'Logout')]
 
#xpath of signupwithemail option
signupwithemail=//div[contains(text(),'Sign up with email')]
 
#id for sign name option
signup_name=profile-name
 
#Actual content for name field
sign_name_content=Sai
 
#xpath of login button for verification
check_login=//button[@type='button']
 
#xpath of Email input field
Email_second=(//input[@id='email'])[1]
 
#Invalid Email
Incorrect_email=abc@abc