#Application URL
baseurl=https://www.snapdeal.com/

#HomePage title
homePageTitle=Shop Online for Men, Women & Kids Clothing, Shoes, Home Decor Items

#Item name
searchItemName=Bluetooth Headphones

#Products page title
productsPageTitle=Snapdeal.com - Online shopping India- Discounts - shop Online Perfumes, Watches, sunglasses etc

#maximum price of the product
maxPrice=900

#minimum price of the product
minPrice=700