#Application URL
baseUrl=https://demo.automationtesting.in/Alerts.html

#alerts page title
alertsPage.expected.title=Alerts

#expected simple alert message
simpleAlert.expected.msg=I am an alert box!

#expected confirm alert message
confirmAlert.expected.msg=You Pressed Cancel

#test data for prompt box
name=Tejas

#expected prompt alert message
promptAlert.expected.msg=Hello Tejas How are you today

#xpath for simple alert button
alertsPage.handleSimpleAlert.xpath=//button[contains(text(),'click the button to display an')]

#xpath for confirm alert button
alertsPage.handleConfirmationAlert.xpath=//button[normalize-space()='click the button to display a confirm box']

#xpath for prompt alert button
alertsPage.handlePromptAlert.xpath=//button[normalize-space()='click the button to demonstrate the prompt box']