#base url link
baseUrl = https://www.google.com

#expected title
expectedTitle = Google

#search suggestions lists
suggestions = //*[@id='Alh6id']/div[1]/div/ul/li

#classname of search suggestions container
searchContainer = erkvQe

#all tab xpath
allTab = //div[@role='navigation']//a[normalize-space()='All']

#iamges tab xpath
imagesTab = //div[@role='navigation']//a[normalize-space()='Images']

#news tab xpath
newsTab = //div[@role='navigation']//a[normalize-space()='News']

#videos tab xpath
videosTab = //div[@role='navigation']//a[normalize-space()='Videos']
